# Enable logging for MCUboot
CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_INF=y

# Enable Serial Recovery over UART
CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_UART=y

CONFIG_PM_PARTITION_SIZE_MCUBOOT=0xF000
# Fix FPROTECT error "Can not FPROTECT region that big" due to size
CONFIG_FPROTECT=n

# Disable UART, since Serial Recovery uses it
CONFIG_UART_CONSOLE=n

# Turn on a LED so we can see when Serial Recovery mode is active
CONFIG_MCUBOOT_INDICATION_LED=y