#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_LOG=y
CONFIG_GPIO=y

CONFIG_DK_LIBRARY=y

CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y

# Additional config to avoid overlapping serial output messages from coredump and logging
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_PRINTK_SYNC=y
CONFIG_LOG_PRINTK=y

# To get all registers (including r4-r11) into the coredump to unwind correctly the call stack
CONFIG_EXTRA_EXCEPTION_INFO=y