# Enable Segger RTT support
CONFIG_USE_SEGGER_RTT=y

# Enable RTT as the backend for the logging and console subsystems
CONFIG_LOG_BACKEND_RTT=y
CONFIG_RTT_CONSOLE=y

# Disable UART console to avoid routing standard output to physical pins
CONFIG_UART_CONSOLE=n

CONFIG_MYFUNCTION=y