# Add MCUboot
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Add private key for MCUboot
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APP_DIR}/private_key.pem"
# SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APP_DIR}/other_key.pem"
# Configure key type
SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y

# SB_CONFIG_MCUBOOT_SIGNATURE_USING_KMU=y
# SB_CONFIG_BOOT_SIGNATURE_TYPE_ED25519=y

# Provision KMU automatically through the build system/nrfutil (nRF54L only)
# SB_CONFIG_MCUBOOT_GENERATE_DEFAULT_KEYFILE=y # This define gives a CMake error right now